apiVersion: apps/v1
kind: Deployment
metadata:
  name: autodeploy77
  labels:
    app: autodeploy77
  namespace: namespace-workflow-1695615898138
spec:
  replicas: 1
  selector:
    matchLabels:
      app: autodeploy77
  template:
    metadata:
      labels:
        app: autodeploy77
    spec:
      containers:
        - name: autodeploy77
          image: acrworkflow1695615898138.azurecr.io/image-workflow-1695615898138:latest
          ports:
            - containerPort: 5000